In [1]:
# add librabry file pandas which is used to read files and tables
import pandas as pd

In [10]:
#Read the datas and stored in avariable called dataset
dataset=pd.read_csv("Salary_Data.csv")
dataset

    YearsExperience    Salary
0               1.1   39343.0
1               1.3   46205.0
2               1.5   37731.0
3               2.0   43525.0
4               2.2   39891.0
5               2.9   56642.0
6               3.0   60150.0
7               3.2   54445.0
8               3.2   64445.0
9               3.7   57189.0
10              3.9   63218.0
11              4.0   55794.0
12              4.0   56957.0
13              4.1   57081.0
14              4.5   61111.0
15              4.9   67938.0
16              5.1   66029.0
17              5.3   83088.0
18              5.9   81363.0
19              6.0   93940.0
20              6.8   91738.0
21              7.1   98273.0
22              7.9  101302.0
23              8.2  113812.0
24              8.7  109431.0
25              9.0  105582.0
26              9.5  116969.0
27              9.6  112635.0
28             10.3  122391.0
29             10.5  121872.0

In [11]:
#save each column in seperate variable so that we can split i/p and o/p

independent=dataset[["YearsExperience"]]
independent

    YearsExperience
0               1.1
1               1.3
2               1.5
3               2.0
4               2.2
5               2.9
6               3.0
7               3.2
8               3.2
9               3.7
10              3.9
11              4.0
12              4.0
13              4.1
14              4.5
15              4.9
16              5.1
17              5.3
18              5.9
19              6.0
20              6.8
21              7.1
22              7.9
23              8.2
24              8.7
25              9.0
26              9.5
27              9.6
28             10.3
29             10.5

dependent=dataset[["Salary"]]
dependent

In [16]:
#Split the training set and test set using library file class name is sklearn using train_test_split fn
#it has four parameters and assigning these four parameters into four different variable
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test=train_test_split(independent,dependent,test_size=.30,random_state=0)
x_train
x_test
y_train
y_test

      Salary
2    37731.0
28  122391.0
13   57081.0
10   63218.0
26  116969.0
24  109431.0
27  112635.0
11   55794.0
17   83088.0

# Model creation using the fn Linear regression ,fit and calculate the weight(slope and bias(initial # value)
from sklearn.linear_model import LinearRegression
regressor= LinearRegression()
regressor.fit(x_train,y_train)
weight=regressor,coef_
weight

In [21]:
#Split the training set and test set using library file class name is sklearn using train_test_split fn
#it has four parameters and assigning these four parameters into four different variable
from sklearn.linear_model import LinearRegression
# regressor is universal variable name to load linear regression file
regressor= LinearRegression()
# fit fn is used calculate the weight(slope) and intial vale bias
regressor.fit(x_train,y_train)
weight=regressor.coef_
weight

array([[9360.26128619]])

In [30]:
# bias is the minimum value means constant value of the slope this value is th o/p of 0 year experience salary
bias=regressor.intercept_
bias

array([26777.3913412])

In [31]:
# Using this model creation evaluate the test values of i/p variable  and find the predicted values of the respected i/p variable
y_prediction=regressor.predict(x_test)
y_prediction

array([[ 40817.78327049],
       [123188.08258899],
       [ 65154.46261459],
       [ 63282.41035735],
       [115699.87356004],
       [108211.66453108],
       [116635.89968866],
       [ 64218.43648597],
       [ 76386.77615802]])

In [32]:
# check predicted value with actual value and calculate R score.If R score value is approximately equal to 1 means, it is the beast mode
# using some lib file r2 score,metrics
from sklearn.metrics import r2_score
r_score=r2_score(y_test,y_prediction)
r_score
# this model find the value y=9360.26128619 * X + 26777.3913412

0.9740993407213511

In [35]:
import pickle
filename="Finalized_Model_creation.sav"
pickle.dump(regressor ,open(filename,'wb'))

In [38]:
#check the model using new values and calculate the salary
loaded_model=pickle.load(open("Finalized_Model_creation.sav",'rb'))
result=loaded_model.predict([[20]])

C:\Anaconda3\Lib\site-packages\sklearn\utils\validation.py:2749: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(

In [37]:
result

array([[213982.61706507]])